### ISSUE TITLE
-H flag not working

### ISSUE THREAD

**Issue by Aneeqasif** [YogeshLamichhane/anime-terminal#1]
-H flags seems to be not working , at first it say episodes out of range and then it open video player for a moment that close by itself after sometime , there might be a bug there

**Comment by YogeshLamichhane** [comment]
### Hi, _Aneeqasif_
Thanks for the report but i couldn't find the error that you've mentioned.
Its working fine for me as you can see in the video below:
Could you provide more details about the issue that you faced?

https://user-images.githubusercontent.com/51807726/130561825-8c1e9ad9-748f-4d62-b1d2-219b1bbf9b3a.mp4
