### ISSUE TITLE
Unrecognized file format

### ISSUE THREAD

**Issue by FernonE** [YogeshLamichhane/anime-terminal#3]
This happens while starting any anime.

![image](https://user-images.githubusercontent.com/49902419/135514678-e61aebd5-0696-49ce-b78c-25e8dc918476.png)

**Comment by YogeshLamichhane** [comment]
Hi @FernonE 
Sorry for the delay in response; I am a bit busy lately.
The script would be fixed soon now.
Have a little patience.

**Comment by YogeshLamichhane** [comment]
It's working for now.
